"""
Motion Planner — ros_interface.py

The /motion_planner node's section-4 settings (base_link, ee_link,
integration_dt, admittance PI gains, force-sensor topics, impedance_sensor,
debug flags) are regular ROS 2 node parameters — COT_MOTION_PLANNER.md does
not document them as startup-only/read-only, so they are fired as live
`ros2 param set` commands, matching the contract in modules/README.md.
The generated params.yaml already uses the correct `integration_dt` key; the
note below only warns about an external/legacy params file that may still
use the outdated `integration_timestep` name.
"""

from typing import List
from app.models.use_case import ROS2Command

_NODE = "/motion_planner"


def get_commands(outputs: dict) -> List[ROS2Command]:
    commands: List[ROS2Command] = []

    # ── Live ros2 param set commands (section 4 of COT_MOTION_PLANNER.md) ───
    commands.append(ROS2Command(
        type="param", node=_NODE, param_name="base_link",
        value=str(outputs.get("base_link", "base_link")),
    ))
    commands.append(ROS2Command(
        type="param", node=_NODE, param_name="ee_link",
        value=str(outputs.get("ee_link", "tcp")),
    ))
    commands.append(ROS2Command(
        type="param", node=_NODE, param_name="ft_link",
        value=str(outputs.get("ft_link", outputs.get("ee_link", "tcp"))),
    ))
    commands.append(ROS2Command(
        type="param", node=_NODE, param_name="integration_dt",
        value=float(outputs.get("integration_dt", 0.001)),
    ))
    commands.append(ROS2Command(
        type="param", node=_NODE, param_name="proportional_gain",
        value=float(outputs.get("proportional_gain", 1 / 3600)),
    ))
    commands.append(ROS2Command(
        type="param", node=_NODE, param_name="integral_gain",
        value=float(outputs.get("integral_gain", 4.6)),
    ))
    commands.append(ROS2Command(
        type="param", node=_NODE, param_name="integral_bound",
        value=float(outputs.get("integral_bound", 0.02)),
    ))
    commands.append(ROS2Command(
        type="param", node=_NODE, param_name="integral_velocity_bound",
        value=float(outputs.get("integral_velocity_bound", 0.01)),
    ))
    commands.append(ROS2Command(
        type="param", node=_NODE, param_name="mini58_topic",
        value=str(outputs.get("mini58_topic", "/ati_ft_sensor/wrench_sensed")),
    ))
    commands.append(ROS2Command(
        type="param", node=_NODE, param_name="nano17_topic",
        value=str(outputs.get("nano17_topic", "/magician_grabber/wrench_sensed")),
    ))
    commands.append(ROS2Command(
        type="param", node=_NODE, param_name="impedance_sensor",
        value=str(outputs.get("impedance_sensor", "force_estimate")),
    ))
    commands.append(ROS2Command(
        type="param", node=_NODE, param_name="debug_prints",
        value=int(bool(outputs.get("debug_prints", False))),
    ))
    commands.append(ROS2Command(
        type="param", node=_NODE, param_name="debug_lib",
        value=int(bool(outputs.get("debug_lib", False))),
    ))

    # ── Operator-facing notes ────────────────────────────────────────────────
    params_yaml = outputs.get("artifacts", {}).get("params_yaml", "")
    if params_yaml:
        commands.append(ROS2Command(
            type="note",
            node=_NODE,
            param_name="params_yaml_path",
            value=params_yaml,
        ))

    if outputs.get("integration_dt_rename_pending"):
        commands.append(ROS2Command(
            type="note",
            node=_NODE,
            param_name="integration_dt_rename_caveat",
            value=(
                "The runtime parameter is `integration_dt`, and motion_planner_params.yaml "
                "(generated by this module) already uses that name correctly. If you instead "
                "launch from an older/legacy params file, check it for the outdated "
                "`integration_timestep` key — the node will silently ignore it and fall back "
                "to its built-in default."
            ),
        ))

    impedance_sensor = str(outputs.get("impedance_sensor", "force_estimate"))
    if impedance_sensor in ("mini58", "nano17"):
        topic = outputs.get("mini58_topic") if impedance_sensor == "mini58" else outputs.get("nano17_topic")
        commands.append(ROS2Command(
            type="note",
            node=_NODE,
            param_name="force_sensor_topic_reminder",
            value=(
                f"impedance_sensor='{impedance_sensor}' reads force from '{topic}'. Confirm this "
                "topic matches the Grabber's configured ATI/Teensy wiring before deploy."
            ),
        ))

    return commands
