"""
Questionnaire schema — single source of truth (previously in backend/routers/questionnaire.py).
Imported by both the GUI form renderer and the questionnaire engine.
"""

SCHEMA = {
    "sections": [
        {"id": "A", "title": "Robot Configuration"},
        {"id": "B", "title": "Sensors & Perception"},
        {"id": "C", "title": "Material & Surface Properties"},
        {"id": "D", "title": "Defect Detection"},
        {"id": "E", "title": "Time & Priority Constraints"},
    ],
    "confidence_categories": [
        {"id": 1, "label": "Robot Arms",        "fields": ["q1_robot_arms"]},
        {"id": 2, "label": "Camera/Sensors",    "fields": ["q2_camera_type", "q3_additional_sensors", "q2_camera_resolution", "q2_camera_framerate", "q2_camera_exposure", "q2_stream_shm"]},
        {"id": 3, "label": "Lighting",          "fields": ["q4_lighting"]},
        {"id": 4, "label": "Material/Size",     "fields": ["q5_materials", "q6_object_size"]},
        {"id": 5, "label": "Defect Types",      "fields": ["q8_defects", "q_clf_model", "q_clf_tile_size", "q_clf_threshold"]},
        {"id": 6, "label": "Time/Profit",       "fields": ["q9_time", "q10_profit"]},
        {"id": 7, "label": "Mesh",              "fields": ["q7_mesh"]},
        {"id": 8, "label": "Grabber Hardware",  "fields": ["q2_camera_framerate", "q3_force_sensor_ip", "q3_lighting_mode", "q3_arduino_path", "q3_teensy_path"]},
        {"id": 9, "label": "Classifier Config", "fields": ["q_clf_model", "q_clf_tile_size", "q_clf_threshold", "q_clf_model_path", "q_clf_use_lasers"]},
    ],
    "questions": [
        {
            "id": "q1_robot_arms",
            "section": "A",
            "title": "Number of robot arms",
            "tooltip": (
                "Select whether your setup uses a single robot arm or multiple coordinated arms. "
                "Multiple arms are needed for tasks requiring parallel operations."
            ),
            "type": "select",
            "options": [
                {"value": "single",   "label": "Single robot arm"},
                {"value": "multiple", "label": "Multiple robot arms"},
            ],
            "follow_up": {
                "condition": {"field": "q1_robot_arms", "value": "multiple"},
                "question": {
                    "id": "q1_num_arms",
                    "type": "number",
                    "label": "How many robot arms?",
                    "min": 2,
                    "max": 10,
                    "default": 2,
                },
            },
        },
        {
            "id": "q2_camera_type",
            "section": "B",
            "title": "Camera type",
            "tooltip": "Choose the type of camera system you are using.",
            "type": "select",
            "options": [
                {"value": "standard", "label": "Standard / Default camera"},
                {"value": "gige",     "label": "GiGE camera"},
                {"value": "other",    "label": "Other camera type"},
            ],
            "follow_up": {
                "condition": {"field": "q2_camera_type", "operator": "in", "values": ["gige", "other"]},
                "question": {
                    "id": "q2_camera_spec",
                    "type": "text",
                    "label": "Specify camera model / type:",
                    "placeholder": "e.g., Basler acA1920-40gc",
                },
            },
        },
        {
            "id": "q2_camera_resolution",
            "section": "B",
            "title": "Camera resolution",
            "tooltip": "Capture resolution in pixels. Used to configure the GigE camera width and height.",
            "type": "dimensions",
            "fields": [
                {"id": "width",  "label": "Width (px)"},
                {"id": "height", "label": "Height (px)"},
            ],
            "units": ["px"],
            "default_unit": "px",
        },
        {
            "id": "q2_camera_framerate",
            "section": "B",
            "title": "Target frame rate (Hz)",
            "tooltip": "Target capture frequency. Rates above 10 Hz require RAM-backed storage (--ram flag).",
            "type": "number",
            "min": 1,
            "max": 200,
            "default": 10,
        },
        {
            "id": "q2_camera_exposure",
            "section": "B",
            "title": "Camera exposure time (µs)",
            "tooltip": "Exposure time in microseconds. Capped at 50 000 µs for safety.",
            "type": "number",
            "min": 1,
            "max": 50000,
            "default": 5000,
        },
        {
            "id": "q2_camera_gain",
            "section": "B",
            "title": "Camera gain",
            "tooltip": "Analogue gain of the camera sensor.",
            "type": "number",
            "min": 0.0,
            "default": 1.0,
        },
        {
            "id": "q2_camera_blacklevel",
            "section": "B",
            "title": "Camera black-level offset",
            "tooltip": "Black-level offset applied to raw pixel values.",
            "type": "number",
            "min": 0.0,
            "default": 0.0,
        },
        {
            "id": "q2_stream_shm",
            "section": "B",
            "title": "Stream frames to shared memory",
            "tooltip": "Publish camera frames to a POSIX shared-memory segment instead of (or alongside) writing files. Required for the live classifier.",
            "type": "select",
            "options": [
                {"value": "yes", "label": "Yes — stream to shared memory"},
                {"value": "no",  "label": "No — file output only"},
            ],
            "follow_up": {
                "condition": {"field": "q2_stream_shm", "value": "yes"},
                "question": {
                    "id": "q2_stream_shm_name",
                    "type": "text",
                    "label": "Shared memory stream name:",
                    "placeholder": "stream1",
                },
            },
        },
        {
            "id": "q3_additional_sensors",
            "section": "B",
            "title": "Additional sensor modalities needed",
            "tooltip": "Select additional sensors needed beyond vision.",
            "type": "checkbox",
            "options": [
                {"value": "tactile", "label": "Tactile / Force sensing (ATI NetFT + Teensy accelerometer)"},
                {"value": "distance", "label": "Distance sensors (Arduino-controlled)"},
                {"value": "vision",  "label": "Additional vision sensors"},
            ],
        },
        {
            "id": "q3_force_sensor_ip",
            "section": "B",
            "title": "ATI NetFT sensor IP address",
            "tooltip": "IP address of the ATI NetFT force/torque sensor. Only used when Tactile / Force sensing is enabled.",
            "type": "text",
            "placeholder": "192.168.137.201",
            "condition": {"field": "q3_additional_sensors", "operator": "contains", "value": "tactile"},
        },
        {
            "id": "q3_force_sensor_port",
            "section": "B",
            "title": "ATI NetFT sensor UDP port",
            "tooltip": "UDP port of the ATI NetFT sensor.",
            "type": "number",
            "min": 1,
            "max": 65535,
            "default": 49152,
            "condition": {"field": "q3_additional_sensors", "operator": "contains", "value": "tactile"},
        },
        {
            "id": "q3_arduino_path",
            "section": "B",
            "title": "Arduino serial port",
            "tooltip": "Serial device path for the Arduino (distance sensor + lighting controller).",
            "type": "text",
            "placeholder": "/dev/ttyUSB0",
            "condition": {"field": "q3_additional_sensors", "operator": "contains", "value": "distance"},
        },
        {
            "id": "q3_teensy_path",
            "section": "B",
            "title": "Teensy serial port",
            "tooltip": "Serial device path for the Teensy (accelerometer).",
            "type": "text",
            "placeholder": "/dev/ttyACM0",
            "condition": {"field": "q3_additional_sensors", "operator": "contains", "value": "tactile"},
        },
        {
            "id": "q3_lighting_mode",
            "section": "B",
            "title": "Lighting controller mode",
            "tooltip": "How the Arduino-controlled lighting reacts to each captured frame.",
            "type": "select",
            "options": [
                {"value": "none",    "label": "No automatic lighting control"},
                {"value": "rlight",  "label": "Round-robin (cycle through lights)"},
                {"value": "dlight",  "label": "Distance-based (react to distance sensors)"},
                {"value": "tlight",  "label": "Pattern-based"},
                {"value": "trigger", "label": "Manual trigger after each frame"},
            ],
            "condition": {"field": "q3_additional_sensors", "operator": "contains", "value": "distance"},
        },
        {
            "id": "q3_tactile_stream",
            "section": "B",
            "title": "Tactile shared memory stream name",
            "tooltip": "POSIX SHM stream name for tactile data output.",
            "type": "text",
            "placeholder": "stream_tactile",
            "condition": {"field": "q3_additional_sensors", "operator": "contains", "value": "tactile"},
        },
        {
            "id": "q4_lighting",
            "section": "B",
            "title": "Lighting conditions",
            "tooltip": "Indicate if ambient lighting is sufficient.",
            "type": "select",
            "options": [
                {"value": "sufficient",  "label": "Sufficient lighting"},
                {"value": "additional",  "label": "Need additional lighting"},
            ],
        },
        {
            "id": "q5_materials",
            "section": "C",
            "title": "Surface materials to work with",
            "tooltip": "Select all material types you need to inspect.",
            "type": "checkbox",
            "options": [
                {"value": "metal",   "label": "Metal (aluminum, steel)"},
                {"value": "wood",    "label": "Wood"},
                {"value": "plastic", "label": "Plastic"},
                {"value": "other",   "label": "Other materials"},
            ],
            "follow_up": {
                "condition": {"field": "q5_materials", "operator": "contains", "value": "other"},
                "question": {
                    "id": "q5_other_material",
                    "type": "text",
                    "label": "Specify other material types:",
                    "placeholder": "e.g., carbon fiber, composite...",
                },
            },
        },
        {
            "id": "q6_object_size",
            "section": "C",
            "title": "Object sizes",
            "tooltip": "Specify the typical size range of objects to inspect.",
            "type": "select",
            "options": [
                {"value": "small",    "label": "Small objects"},
                {"value": "large",    "label": "Large objects (e.g., boats, vehicles)"},
                {"value": "variable", "label": "Variable sizes"},
            ],
            "follow_up": {
                "condition": {"field": "q6_object_size", "operator": "in", "values": ["large", "variable"]},
                "question": {
                    "id": "q6_dimensions",
                    "type": "dimensions",
                    "label": "Approximate object dimensions:",
                    "fields": [
                        {"id": "length", "label": "Length"},
                        {"id": "width",  "label": "Width"},
                        {"id": "height", "label": "Height"},
                    ],
                    "units": ["m", "cm", "mm"],
                    "default_unit": "m",
                },
            },
        },
        {
            "id": "q7_mesh",
            "section": "C",
            "title": "3D mesh availability",
            "tooltip": "Indicate whether a 3D mesh or CAD model of the object is available.",
            "type": "select",
            "options": [
                {"value": "available",       "label": "Available"},
                {"value": "in_preparation",  "label": "In preparation"},
                {"value": "not_available",   "label": "Not available"},
            ],
            "follow_up": {
                "condition": {"field": "q7_mesh", "value": "in_preparation"},
                "question": {
                    "id": "q7_mesh_status",
                    "type": "select",
                    "label": "Current mesh status:",
                    "options": [
                        {"value": "cad",      "label": "CAD model exists"},
                        {"value": "scanning", "label": "Needs 3D scanning"},
                        {"value": "unknown",  "label": "Unknown"},
                    ],
                },
            },
        },
        {
            "id": "q8_defects",
            "section": "D",
            "title": "Types of defects to detect",
            "tooltip": "Select all defect types relevant to your application.",
            "type": "checkbox",
            "options": [
                {"value": "dents",          "label": "Dents / Deformations"},
                {"value": "dirt",           "label": "Dirt / Contamination"},
                {"value": "surface_damage", "label": "Surface damage"},
            ],
        },
        # --- Magician Vision Classifier configuration ---
        {
            "id": "q_clf_model",
            "section": "D",
            "title": "Classifier backbone architecture",
            "tooltip": "Neural network backbone used for tile classification. resnet18 is a good default; larger models are more accurate but slower.",
            "type": "select",
            "options": [
                {"value": "resnet18",          "label": "ResNet-18 (recommended)"},
                {"value": "resnext50",         "label": "ResNeXt-50"},
                {"value": "convnext_tiny",     "label": "ConvNeXt Tiny"},
                {"value": "efficientnet_v2_s", "label": "EfficientNet V2 S"},
                {"value": "swin_v2_t",         "label": "Swin Transformer V2 T"},
                {"value": "efficientnet_b0",   "label": "EfficientNet B0"},
                {"value": "mobilenet_v3_small","label": "MobileNet V3 Small"},
                {"value": "custom_cnn",        "label": "Custom small CNN"},
            ],
        },
        {
            "id": "q_clf_tile_size",
            "section": "D",
            "title": "Classifier tile size (pixels)",
            "tooltip": "Side length of the square tiles fed to the classifier. Must match the value used during training. Smaller tiles are faster but capture less context.",
            "type": "select",
            "options": [
                {"value": "32",  "label": "32 px (fast, less context)"},
                {"value": "48",  "label": "48 px (default)"},
                {"value": "64",  "label": "64 px (more context, slower)"},
                {"value": "128", "label": "128 px (high context, much slower)"},
            ],
        },
        {
            "id": "q_clf_step_size",
            "section": "D",
            "title": "Inference tile step size (pixels)",
            "tooltip": "Pixel stride between tiles during live inference. Smaller values produce denser heatmaps but increase computation.",
            "type": "number",
            "min": 1,
            "max": 128,
            "default": 18,
        },
        {
            "id": "q_clf_threshold",
            "section": "D",
            "title": "Detection confidence threshold",
            "tooltip": "Minimum softmax confidence required to register a tile as a defect. Tiles below this are reassigned to the low-confidence class.",
            "type": "number",
            "min": 0.0,
            "max": 1.0,
            "default": 0.6,
        },
        {
            "id": "q_clf_fps",
            "section": "D",
            "title": "Target inference frame rate (FPS)",
            "tooltip": "Maximum frame rate for the live classifier. Set to 0 for unlimited.",
            "type": "number",
            "min": 0.0,
            "default": 23.0,
        },
        {
            "id": "q_clf_majority_voting",
            "section": "D",
            "title": "Enable majority voting",
            "tooltip": "Apply a 3×3 spatial majority-vote filter to smooth classifier predictions and suppress isolated false positives.",
            "type": "select",
            "options": [
                {"value": "yes", "label": "Yes (recommended)"},
                {"value": "no",  "label": "No"},
            ],
        },
        {
            "id": "q_clf_two_stage",
            "section": "D",
            "title": "Enable two-stage ensemble classification",
            "tooltip": "Use a full model ensemble (binary filter → multi-class) for higher accuracy at the cost of increased GPU usage.",
            "type": "select",
            "options": [
                {"value": "no",  "label": "No — single model (faster)"},
                {"value": "yes", "label": "Yes — two-stage ensemble (more accurate)"},
            ],
        },
        {
            "id": "q_clf_model_path",
            "section": "D",
            "title": "Path to pre-trained model checkpoint",
            "tooltip": "Absolute path to an existing .pth file. If provided, training is skipped. Leave empty to generate a training configuration instead.",
            "type": "text",
            "placeholder": "/path/to/allclass_resnet18.pth",
        },
        {
            "id": "q_clf_dataset_dir",
            "section": "D",
            "title": "Training dataset directory",
            "tooltip": "Path to the annotated tile dataset (keras_dataset/ layout). Required only when no pre-trained model is provided.",
            "type": "text",
            "placeholder": "/path/to/keras_dataset/",
            "condition": {"field": "q_clf_model_path", "operator": "empty"},
        },
        {
            "id": "q_clf_epochs",
            "section": "D",
            "title": "Training epochs",
            "tooltip": "Number of full passes over the training dataset.",
            "type": "number",
            "min": 1,
            "default": 10,
            "condition": {"field": "q_clf_model_path", "operator": "empty"},
        },
        {
            "id": "q_clf_batch_size",
            "section": "D",
            "title": "Training batch size",
            "tooltip": "Number of tiles per gradient update. Reduce if GPU memory is insufficient.",
            "type": "number",
            "min": 1,
            "default": 64,
            "condition": {"field": "q_clf_model_path", "operator": "empty"},
        },
        {
            "id": "q_clf_learning_rate",
            "section": "D",
            "title": "Learning rate",
            "tooltip": "AdamW optimiser learning rate.",
            "type": "number",
            "min": 1e-6,
            "default": 0.0005,
            "condition": {"field": "q_clf_model_path", "operator": "empty"},
        },
        {
            "id": "q_clf_loss",
            "section": "D",
            "title": "Training loss function",
            "tooltip": "focal loss handles class imbalance well; cross_entropy is simpler.",
            "type": "select",
            "options": [
                {"value": "focal",         "label": "Focal loss (recommended for imbalanced classes)"},
                {"value": "cross_entropy", "label": "Cross-entropy"},
            ],
            "condition": {"field": "q_clf_model_path", "operator": "empty"},
        },
        {
            "id": "q_clf_use_lasers",
            "section": "D",
            "title": "Enable laser distance sensor fusion",
            "tooltip": "Subscribe to distance sensor topics and fuse depth into detection messages using IDW interpolation.",
            "type": "select",
            "options": [
                {"value": "yes", "label": "Yes — use laser depth fusion"},
                {"value": "no",  "label": "No — 2D detections only"},
            ],
        },
        {
            "id": "q_clf_laser_topic_1",
            "section": "D",
            "title": "Laser sensor topic 1",
            "tooltip": "ROS 2 topic for the first distance sensor.",
            "type": "text",
            "placeholder": "magician_grabber/distance1",
            "condition": {"field": "q_clf_use_lasers", "value": "yes"},
        },
        {
            "id": "q_clf_laser_topic_2",
            "section": "D",
            "title": "Laser sensor topic 2",
            "tooltip": "ROS 2 topic for the second distance sensor.",
            "type": "text",
            "placeholder": "magician_grabber/distance2",
            "condition": {"field": "q_clf_use_lasers", "value": "yes"},
        },
        {
            "id": "q_clf_laser_topic_3",
            "section": "D",
            "title": "Laser sensor topic 3",
            "tooltip": "ROS 2 topic for the third distance sensor.",
            "type": "text",
            "placeholder": "magician_grabber/distance3",
            "condition": {"field": "q_clf_use_lasers", "value": "yes"},
        },
        {
            "id": "q_clf_laser_px1_x",
            "section": "D",
            "title": "Laser 1 pixel position — X",
            "tooltip": "X coordinate (pixels) of laser 1 in the camera image plane.",
            "type": "number",
            "default": 120,
            "condition": {"field": "q_clf_use_lasers", "value": "yes"},
        },
        {
            "id": "q_clf_laser_px1_y",
            "section": "D",
            "title": "Laser 1 pixel position — Y",
            "tooltip": "Y coordinate (pixels) of laser 1 in the camera image plane.",
            "type": "number",
            "default": 200,
            "condition": {"field": "q_clf_use_lasers", "value": "yes"},
        },
        {
            "id": "q_clf_laser_px2_x",
            "section": "D",
            "title": "Laser 2 pixel position — X",
            "type": "number",
            "default": 320,
            "condition": {"field": "q_clf_use_lasers", "value": "yes"},
        },
        {
            "id": "q_clf_laser_px2_y",
            "section": "D",
            "title": "Laser 2 pixel position — Y",
            "type": "number",
            "default": 200,
            "condition": {"field": "q_clf_use_lasers", "value": "yes"},
        },
        {
            "id": "q_clf_laser_px3_x",
            "section": "D",
            "title": "Laser 3 pixel position — X",
            "type": "number",
            "default": 520,
            "condition": {"field": "q_clf_use_lasers", "value": "yes"},
        },
        {
            "id": "q_clf_laser_px3_y",
            "section": "D",
            "title": "Laser 3 pixel position — Y",
            "type": "number",
            "default": 200,
            "condition": {"field": "q_clf_use_lasers", "value": "yes"},
        },
        {
            "id": "q_clf_laser_idw_power",
            "section": "D",
            "title": "Laser IDW interpolation power",
            "tooltip": "Power parameter for Inverse Distance Weighting depth interpolation.",
            "type": "number",
            "min": 0.1,
            "default": 2.0,
            "condition": {"field": "q_clf_use_lasers", "value": "yes"},
        },
        # --- Advanced: polarization channel selection ---
        {
            "id": "q_clf_advanced",
            "section": "D",
            "title": "Configure advanced polarization channels",
            "tooltip": "AoLP, DoLP, and unpolarized are extra input channels derived from the 4 Stokes channels. These are baked into the model at training time.",
            "type": "select",
            "options": [
                {"value": "no",  "label": "No — use standard 4-channel input"},
                {"value": "yes", "label": "Yes — configure advanced channel options"},
            ],
        },
        {
            "id": "q_clf_aolp",
            "section": "D",
            "title": "Include Angle of Linear Polarization (AoLP) channel",
            "tooltip": "Adds an AoLP-derived channel to the model input. Must match training configuration.",
            "type": "select",
            "options": [
                {"value": "no",  "label": "No"},
                {"value": "yes", "label": "Yes"},
            ],
            "condition": {"field": "q_clf_advanced", "value": "yes"},
        },
        {
            "id": "q_clf_dolp",
            "section": "D",
            "title": "Include Degree of Linear Polarization (DoLP) channel",
            "tooltip": "Adds a DoLP-derived channel to the model input. Must match training configuration.",
            "type": "select",
            "options": [
                {"value": "no",  "label": "No"},
                {"value": "yes", "label": "Yes"},
            ],
            "condition": {"field": "q_clf_advanced", "value": "yes"},
        },
        {
            "id": "q_clf_unpolarized",
            "section": "D",
            "title": "Include unpolarized (mean intensity) channel",
            "tooltip": "Adds the mean of the 4 polarization channels as an extra input channel.",
            "type": "select",
            "options": [
                {"value": "no",  "label": "No"},
                {"value": "yes", "label": "Yes"},
            ],
            "condition": {"field": "q_clf_advanced", "value": "yes"},
        },
        {
            "id": "q9_time",
            "section": "E",
            "title": "Time constraints",
            "tooltip": "Indicate if your inspection task has time limits.",
            "type": "select",
            "options": [
                {"value": "none",  "label": "No time constraints"},
                {"value": "tight", "label": "Tight deadlines / timeframe required"},
            ],
            "follow_up": {
                "condition": {"field": "q9_time", "value": "tight"},
                "question": {
                    "id": "q9_time_value",
                    "type": "number_with_unit",
                    "label": "Specify time constraint:",
                    "min": 0,
                    "default": 2,
                    "units": ["seconds", "minutes", "hours"],
                    "default_unit": "minutes",
                    "unit_field": "q9_time_unit",
                },
            },
        },
        {
            "id": "q10_profit",
            "section": "E",
            "title": "Profit / priority definition",
            "tooltip": "Choose how to prioritise inspection areas.",
            "type": "select",
            "options": [
                {"value": "standard", "label": "Standard profit calculation"},
                {"value": "custom",   "label": "Custom profit / priority criteria"},
            ],
        },
    ],
}
